version: '2'
services:
  web:
    build: web
    ports:
     - 3838:3838
    volumes:
     - ./web/:/srv/shiny-server/twi/
     - ./log/:/var/log/shiny-server/
    depends_on:
     - redis
  worker:
    build: worker
    volumes:
     - ./worker/:/usr/src/app/
    depends_on:
     - redis
  redis:
    image: redis:alpine
    ports:
     - 6379:6379
    volumes:
     - ..:/data
